### PR TITLE
Use setup.py as source of truth for deps

### PR DESCRIPTION
**Pull request by FlorianKempenich**
After our discussion @lifeisafractal where you mentioned your process for creating the dev virtual env:
1. Create a virtual env
1. Install `appdaemontestframework`
1. Start working

Step 2. is key because by installing `appdaemontestframework` directly in the local virtual env, it'll automatically install all the dependencies of the `setup.py`. So no need to replicate anything in the `Pipfile`

It seems almost too simple to work, but I can't seem to see any catch. It does work as expected locally. Let me know if you think it's good as well, and we can merge.

### CODE REVIEW

**Comment by lifeisafractal** [comment]
This looks great, glad we talk this out quickly.

My only question is if there should be a quick reference to using `pipenv` for devlopment in the `README.md` maybe in the [Contributing](https://github.com/FlorianKempenich/Appdaemon-Test-Framework#contributing) section, or adding a Development section for this and future development details. Totally not required, just thinking about how I missed the whole pipenv thing at first when diving in.

Other than that, looks good to go from my point of view.

**Comment by FlorianKempenich** [comment]
Oh good point. I'll add that,  1 sec

**Comment by FlorianKempenich** [comment]
@lifeisafractal I just updated the README. 
1. Removed warning about tests being not reliable (it's not true anymore)
1. Added a guide for Pipenv
If it's good . . . let this be the first PR you merge yourself 😊

**Comment by FlorianKempenich** [comment]
Then you can merge it 😁

**Comment by FlorianKempenich** [comment]
Wohoo 🎉 The first PR you merged. 🎉
Congrats 😃

**Comment by lifeisafractal** [comment]
Thanks! 🎉 🎉

**Pull request merged**
