### PR TITLE
fix include

### PR DESCRIPTION
**Pull request by fhoekstra**
I also took the chance to:
- update python version in setup.py
- increment version of the distribution, just to be sure

I tested it by building the wheel and re-running the tests after installing the wheel with pip, issue #57 was resolved afterward.

### CODE REVIEW

**Comment by FlorianKempenich** [comment]
Would this work without any arguments to `find_packages`? 

Like [this stackoverflow answer](https://stackoverflow.com/a/43794884) suggests.

**Comment by fhoekstra** [comment]
It probably does, but I think we may start shipping some of the folders in test then, if they have an __init__.py file. So that may be worth checking

**Comment by fhoekstra** [comment]
I just did that, renamed the resulting .whl file's extension to .zip and took a look inside. The result seems to be the same.

**Comment by FlorianKempenich** [comment]
Awesome! Thanks for your contribution 😃
I'm merging 👍

**Comment by FlorianKempenich** [comment]
And I've just released `v4.0.0b2`. It'll be up in a few minutes.

**Pull request merged**
